apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aggregation-service
spec:
  schedule: "*/10 * * * *" # every 10 mins 
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregation-service
            image: tylerhanson1/aggregation_service
            env:
              - name: database_url
                valueFrom:
                  configMapKeyRef:
                    name: app-config
                    key: database_url
              - name: db_user
                valueFrom:
                  configMapKeyRef:
                    name: app-config
                    key: db_user
              - name: db_password
                valueFrom:
                  configMapKeyRef:
                    name: app-config
                    key: db_password
              - name: database_name
                valueFrom:
                  configMapKeyRef:
                    name: app-config
                    key: database_name
            command: ["python"]
            args: ["main.py"]
          restartPolicy: Never